---
# - name: update web and nfs aservers
#   hosts: webservers, nfs
#   remote_user: ec2-user
#   become: yes
#   become_user: root
#   tasks:
#     - name: ensure wireshark is at the latest version
#       yum:
#         name: wireshark
#         state: latest

- name: update LB server
  hosts: tooling, todo
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes
      tags:
        - webservers

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest
      tags:
        - webservers

- name: For all servers
  hosts: all
  remote_user: root
  become_user: root
  become: yes
  tasks:
    - name: Set timezone to Africa/Lagos
      community.general.timezone:
        name: Africa/Lagos
   
    - name: Create a directory
      ansible.builtin.file:
        path: /tmp/shell_folder
        state: directory
        mode: '0777'

    - name: Create a file
      ansible.builtin.file:
        path: /tmp/shell_folder/just_file.sh
        state: touch
        mode: '0777'
        
    - name: Execute a script
      script: /tmp/shell_folder/just_file.sh
