---
# - name: Include dynamic variables
#   hosts: all
#   tasks:
#   - import_playbook: ../static-assignments/common.yml 
#   - include_vars: ../dynamic-assignments/env-vars.yml
#   tags:
#     - always

# - name: Loadbalancers assignment
#   hosts: lb
# - import_playbook: ../static-assignments/loadbalancers.yml
#   when: load_balancer_is_required 

- hosts: webservers
- name: Webserver assignment
  import_playbook: ../static-assignments/webservers.yml

# - hosts: all
# - import_playbook: ../static-assignments/common.yml