---
- name: Include dynamic variables
  hosts: all
  tasks:
  - import_tasks: ../static-assignments/common.yml

# - name: Loadbalancers assignment
#   hosts: lb
# - import_playbook: ../static-assignments/loadbalancers.yml
#   when: load_balancer_is_required 

# - name: Include dynamic variables
#   hosts: all
#   tasks:
#   - include_tasks: ../dynamic-assignment/env_vars.yml
#     tags:
#       - always